@echo off
del "..\*.png*"
del "..\*.bmp*"
del "..\*.jpg*"
del "..\*.jpeg*"
del "..\*.jfif*"
del "..\*.sfo*"
del "..\input\*.png*"
del "..\input\*.bmp*"
del "..\input\*.jpg*"
del "..\input\*.jpeg*"
del "..\input\*.jfif*"
rmdir /S /Q "..\vpk\input"
rmdir /S /Q "..\vpk\output"
md "..\vpk\input"
md "..\vpk\output"
exit
